### ISSUE TITLE
check_missing option

### ISSUE THREAD

**Issue by lisu-stats** [CAM-Roche/TrialEmulation#100]
Hi, @gravesti Should we add the `check_missing` option? Right now, it is in the help files of `data_preparation` and `data_modelling`. Below are the comments from the SAS macro on this option. Thanks.
```
 %if &check_missing=1 %then %do;
            /*********** 
            check for missing values in variables in final models, when use_censor = 1 only missing
            values should be in _case variable due to censoring at a change in treatment. When 
            use_censor = 0 there should be no missing values ( what about original missing outcome
            due to censoring in original data
             ***********/
            proc means data = _switch_pass n nmiss ;
            var  &outcome  &model_var &outcomeCov  
                      %if &include_expansion_time_case = 1 %then for_period for_period2 ;
                      %if %eval(&include_followup_time_case) = 1 %then &followup_var ; ; 
           run;
        %end;
```

**Comment by gravesti** [comment]
I don't think we need an option. By default glm will do a complete case analysis, so we don't have to worry about errors. Maybe we just add a warning message if missing data is found.

**Comment by lisu-stats** [comment]
Yes @gravesti , I think a warning message would be sufficient. 

By the way, I am thinking of slightly changing the package title. How about 'Design and conduct of causal analyses of observational time-to-event data using target trial emulation'? I think it would be useful to highlight it is the causal analyses that the package does.  Thanks.

**Comment by gravesti** [comment]
@lisu-stats Ok this sounds good. I'll update both of these.
