### ISSUE TITLE
rename package: TrialEmulation

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/TrialEmulation#96]
- [x] Search and rename in description, vignettes etc. 
- [x] Rename repo

**Comment by lisu-stats** [comment]
Thanks @gravesti for updating the package name. I wonder for the citation of the package, should we make it clear that it is for time-to-event outcomes? 
 
Would the following work?
TrialEmulation: Design and analysis of target trial emulation using observational time-to-event data. R package version 0.0.2.10.
